// Supabase runtime info (was autogenerated in previous builds).
// In this repo, values are provided via Vercel environment variables.
// No keys are committed.

import { SUPABASE_URL, SUPABASE_ANON_KEY } from '../../lib/env';

export const projectId = (() => {
  try {
    const host = new URL(SUPABASE_URL).host; // <project>.supabase.co
    return host.split('.')[0] || '';
  } catch {
    return '';
  }
})();

export const publicAnonKey = SUPABASE_ANON_KEY;
