/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "rfoftonnlwudilafhfkl"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmb2Z0b25ubHd1ZGlsYWZoZmtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NTg4MTAsImV4cCI6MjA2OTIzNDgxMH0.W4g28oa8m-KkaLhgpkoyHW2fo5Jec1K-vfeRVxAhFdI"