/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */
/* 🔒 SECURITY: This file now uses environment variables instead of hardcoded values */

// Extract project ID from environment variable URL
// Expected format: https://{projectId}.supabase.co
function getProjectIdFromUrl(url: string): string {
  const match = url.match(/https:\/\/([^.]+)\.supabase\.co/);
  if (!match || !match[1]) {
    throw new Error(
      'Invalid VITE_SUPABASE_URL format. Expected: https://your-project.supabase.co'
    );
  }
  return match[1];
}

// Get credentials from environment variables with validation
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const anonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl) {
  throw new Error(
    'VITE_SUPABASE_URL is required. Add it to .env.local\n' +
    'Example: VITE_SUPABASE_URL=https://your-project.supabase.co'
  );
}

if (!anonKey) {
  throw new Error(
    'VITE_SUPABASE_ANON_KEY is required. Add it to .env.local\n' +
    'Get it from: Supabase Dashboard > Settings > API > Project API keys'
  );
}

export const projectId = getProjectIdFromUrl(supabaseUrl);
export const publicAnonKey = anonKey;