/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */
/* 🔒 SECURITY: This file now uses environment variables instead of hardcoded values */

// Extract project ID from environment variable URL
// Expected format: https://{projectId}.supabase.co
// Note: This pattern assumes standard Supabase URLs. Custom domains are not currently supported.
function getProjectIdFromUrl(url: string): string {
  // Try standard Supabase URL pattern first
  const supabaseMatch = url.match(/https:\/\/([^.]+)\.supabase\.co/);
  if (supabaseMatch && supabaseMatch[1]) {
    return supabaseMatch[1];
  }
  
  // For custom domains, extract the subdomain or use a fallback approach
  // This is a basic implementation - you may need to adjust based on your setup
  const customMatch = url.match(/https:\/\/([^.]+)\./);
  if (customMatch && customMatch[1]) {
    console.warn('Using custom Supabase domain. Project ID extraction may not be accurate.');
    return customMatch[1];
  }
  
  throw new Error(
    'Invalid VITE_SUPABASE_URL format. Expected: https://your-project.supabase.co\n' +
    'If using a custom domain, please ensure the URL is correctly formatted.'
  );
}

// Get credentials from environment variables with validation
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const anonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl) {
  throw new Error(
    'VITE_SUPABASE_URL is required. Add it to .env.local\n' +
    'Example: VITE_SUPABASE_URL=https://your-project.supabase.co'
  );
}

if (!anonKey) {
  throw new Error(
    'VITE_SUPABASE_ANON_KEY is required. Add it to .env.local\n' +
    'Get it from: Supabase Dashboard > Settings > API > Project API keys'
  );
}

export const projectId = getProjectIdFromUrl(supabaseUrl);
export const publicAnonKey = anonKey;