/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */
/* 🔒 SECURITY: This file now uses environment variables instead of hardcoded values */

// Extract project ID from environment variable URL
// Expected format: https://{projectId}.supabase.co
// Note: This pattern assumes standard Supabase URLs. Custom domains are not currently supported.
function getProjectIdFromUrl(url: string): string {
  const normalized = url.trim().replace(/^['"]|['"]$/g, '').replace(/\/+$/g, '');

  // Prefer URL parsing (handles custom domains reliably)
  try {
    const parsed = new URL(normalized);
    const host = parsed.hostname;
    if (host.endsWith('.supabase.co')) {
      return host.split('.')[0] || '';
    }

    // Custom domains: best-effort extraction (subdomain), may not equal Supabase project ref.
    const firstLabel = host.split('.')[0];
    if (firstLabel) {
      console.warn('Using custom Supabase domain. Project ID extraction may not be accurate.');
      return firstLabel;
    }
  } catch {
    // Fall back to regex below
  }

  // Try standard Supabase URL pattern (supports http/https)
  const supabaseMatch = normalized.match(/https?:\/\/([^.]+)\.supabase\.co/i);
  if (supabaseMatch && supabaseMatch[1]) return supabaseMatch[1];

  // Custom domain fallback (supports http/https)
  const customMatch = normalized.match(/https?:\/\/([^.]+)\./i);
  if (customMatch && customMatch[1]) {
    console.warn('Using custom Supabase domain. Project ID extraction may not be accurate.');
    return customMatch[1];
  }
  
  throw new Error(
    'Invalid VITE_SUPABASE_URL format. Expected: https://your-project.supabase.co\n' +
    'If using a custom domain, please ensure the URL is correctly formatted.'
  );
}

// Get credentials from environment variables with validation
const supabaseUrl = (import.meta.env.VITE_SUPABASE_URL as string | undefined)?.trim();
const anonKey = (import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined)?.trim();

if (!supabaseUrl) {
  throw new Error(
    'VITE_SUPABASE_URL is required. Add it to .env.local\n' +
    'Example: VITE_SUPABASE_URL=https://your-project.supabase.co'
  );
}

if (!anonKey) {
  throw new Error(
    'VITE_SUPABASE_ANON_KEY is required. Add it to .env.local\n' +
    'Get it from: Supabase Dashboard > Settings > API > Project API keys'
  );
}

export const projectId = getProjectIdFromUrl(supabaseUrl);
export const publicAnonKey = anonKey;